Repository Geetika-2001/CodingSimplified_GK, pull requests merged in 2021-11, with the labels that each got.

#119 Create selection sort_sart.cpp
  selection sort_sart.cpp
Labels: hacktoberfest-accepted, hacktoberfest2021

#118 pls merge this
  Linear Search.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#120 Adding cpp file
  CPP/fstream.cpp
Labels: good first issue
