Repository Geetika-2001/CodingSimplified_GK, pull requests merged in 2021-10, with the labels that each got.

#55 pp.java
  Java/pp.java
Labels: hacktoberfest, hacktoberfest-accepted

#54 matrices_addition
  CPP/matrices_addition.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#53 Sum of matrix
  matrixsum.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#52 Added problem -All connected components in a graph
  CPP/allconnectedcomponents.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#51 Add problem - Closest Pair of Points using DNC
  CPP/closest.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#50 Adding the file finally
  Python/Collections.py
  Python/DateTime.py
Labels: hacktoberfest, hacktoberfest-accepted

#59 Create zip
  py/zip
Labels: hacktoberfest, hacktoberfest-accepted

#58 Create mergetwofiles
  CPP/mergetwofiles
Labels: hacktoberfest, hacktoberfest-accepted

#57 Create AllindexOfNumberUsingRecurssion.cpp
  CPP/AllindexOfNumberUsingRecurssion.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#61 Create FILE1
  CPP/FILE1
Labels: hacktoberfest, hacktoberfest-accepted

#60 Create FirstIndexOfNumberUsingRecurssion.cpp
  CPP/FirstIndexOfNumberUsingRecurssion.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#62 Create LastindexOfNumberUsingRecurssion.cpp
  CPP/LastindexOfNumberUsingRecurssion.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#63 Create Sets
  py/Sets
Labels: hacktoberfest, hacktoberfest-accepted

#64 Create py
  Turtles/py
Labels: hacktoberfest, hacktoberfest-accepted

#74 Greedy Solution to Change-making problem
  CPP/coinchange.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#73 Added Prim's Algorithm
  CPP/prims.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#72 3 Way Quick Sort
  CPP/ThreeWayQuickSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#71 Added Dijkstra's Algorithm
  CPP/Dijkstras.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#70 Create fah_to-celcius
  CPP/fah_to-celcius
Labels: hacktoberfest, hacktoberfest-accepted

#69 Problem & Solution to Number of inverions using merge sort added
  inversion.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#68 Added BFS traversal in a graph
  CPP/bfstraversal.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#67 Create pp4
  java/pp4
Labels: hacktoberfest, hacktoberfest-accepted

#66 Create pp3
  java/pp3
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#65 Create pp2
  java/pp2
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#75 Create Minesweeper code.cpp
  Minesweeper code.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#86 Create Sine_Cosine_Table.cpp
  CPP/Sine_Cosine_Table.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#85 Added PI_from_Random.py
  Python/PI_from_Random.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#84 Added Floyd's Algorithm for Python
  Python/Floyd_Warshall_Algorithm.py
Labels: hacktoberfest, hacktoberfest-accepted

#83 Added Floyd Warshall Algorithm for C++
  CPP/Floyd_Warshall_Algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#82 add-nos
  CPP/add-nos
Labels: hacktoberfest, hacktoberfest-accepted

#81 Create mergetwolists
  CPP/mergetwolists
Labels: hacktoberfest, hacktoberfest-accepted

#80 Added counting sort
  Java/countsort.java
Labels: hacktoberfest, hacktoberfest-accepted

#79 Added Kadane's Algorithm
  Java/kadanealgo.java
Labels: hacktoberfest, hacktoberfest-accepted

#78 Added Floyd's Algorithm
  Java/FindLoop.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#77 Create add-sub-poly
  CPP/add-sub-poly
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#76 linked_list.c
  C/linked_list.c
Labels: hacktoberfest, hacktoberfest-accepted

#90 Added Linked List
  Java/singleLinkedList.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#89 Create GuessingTheNumber.c
  GuessingTheNumber.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#88 create Python Program for Insertion Sort
  Python_Program_for_Insertion_Sort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#87 Create Linear Algebra.py
  Python/Linear Algebra.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#92 Added Node Search in Binary Tree
  Java/nodesearchBinaryTree.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#91 Create A_Lucky_Division.cpp
  CPP/A_Lucky_Divison.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#93 Create OnlyAlpha.java
  java/OnlyAlpha.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#94 Create Sum_Of_Digits.java
  java/Sum_Of_Digits.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#114 Create perfect_guess.py
  perfect_guess.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#113 Create Snake_water.py
  Snake_water.py
Labels: hacktoberfest, hacktoberfest2021

#112 Create Calender.py
  Calender.py
Labels: hacktoberfest, hacktoberfest-accepted

#111 create Calculator.py
  Calculator.py
Labels: hacktoberfest, hacktoberfest-accepted

#110 Create GetterSetter.cpp
  GetterSetter.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#109 Create CopyConstructor.cpp
  CopyConstructor.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#108 Create Using_Constructor_For_Compulsory_Input.cpp
  Using_Constructor_For_Compulsory_Input.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#115 Create I_wanna_be_the_guy.cpp
  CPP/I_wanna_be_the_guy.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#107 Create Constructor.pp
  Constructor.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#106 Binary_tree.cpp
  CPP/Binary_tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#105 create python program for numpy lexsort
  Python/python_progam_for_numpy_lexsort.py
Labels: hacktoberfest, hacktoberfest-accepted

#104 create python program for numpy argsort
  Python/python_program_for_numpy_argsort.py
Labels: hacktoberfest, hacktoberfest-accepted

#103 Create Dynamicarrayusinglinkedlist.cpp
  CPP/Dynamicarrayusinglinkedlist.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#102 Create Destructor.cpp
  CPP/Destructor.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#100 Create Dynamicqueue.cpp
  CPP/Dynamicqueue.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#99 Create Python Program for Selection Sort
  Python/Python_Program_for_Selection_Sort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#98 Create Stackusinglinkedlist.cpp
  CPP/Stackusinglinkedlist.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#116 Create merge sort
  merge sort
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#97 Create RadixSort.py
  RadixSort.py
Labels: hacktoberfest, hacktoberfest-accepted

#96 majority element by MOORE'S VOTING Algorithm
  CPP/majority_element.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#117 Create Arrival_of_the_general.cpp
  CPP/Arrival_of_the_general.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#95 Create Anton_&_Letters.cpp
  CPP/Anton_&_Letters.cpp
Labels: hacktoberfest, hacktoberfest-accepted
